### ISSUE TITLE
中国语言crawl.py验证码ocr报错

### ISSUE THREAD

**Issue by yimingzhou233** [lernanto/sinetym#13]
你好，爬取在验证码ocr这一步报错，想请教一下可能是什么问题，代码只改了43行rsp = session.get(verify_code_url,verify=False)，之前这一步会报错
INFO:root:get verify code from https://zhongguoyuyan.cn/svc/common/create/verifyCode
Traceback (most recent call last):
  File "/mnt/c/Users/ymzhou/Downloads/crawl.py", line 586, in <module>
    main()
  File "/mnt/c/Users/ymzhou/Downloads/crawl.py", line 582, in main
    crawl(email, password, prefix)
  File "/mnt/c/Users/ymzhou/Downloads/crawl.py", line 411, in crawl
    session = try_login(email, password)
  File "/mnt/c/Users/ymzhou/Downloads/crawl.py", line 189, in try_login
    token = get_token(image, ocr)
  File "/mnt/c/Users/ymzhou/Downloads/crawl.py", line 52, in get_token
    token = ocr.classification(image)
  File "/home/ymzhou/.local/lib/python3.10/site-packages/ddddocr/__init__.py", line 1605, in classification
    image = Image.open(io.BytesIO(img))
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa03375c090>

**Comment by lernanto** [comment]
网站改版了，现有的爬取逻辑不适用了，我还没时间研究改版后的怎么爬。

**Comment by kangj13** [comment]
期待早日修复。对您的研究很感兴趣。感谢

**Comment by lernanto** [comment]
我当前的关注点暂时不在这里。我已经整理了一份小学堂的数据集，格式和语保数据集很相似，可以作为替代。同时也希望有余力的同好鼎力相助处理这个问题。

**Comment by kalvinchang** [comment]
我用了chrome network inspector 發現新的verify_code_url 跟舊的很像

https://zhongguoyuyan.cn/api/common/create/verifyCode
instead of
https://zhongguoyuyan.cn/svc/common/create/verifyCode

**Comment by kalvinchang** [comment]
用新的 verifyCode endpoint, get_verify_code 會輸出一個valid image 的 bytestring
